# fly.toml app configuration file generated for porto-stcp-realtime on 2023-09-23T11:58:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "porto-stcp-realtime"
primary_region = "mad"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[build]

[env]
  PORT = "8080"

[processes]
  app = "run --allow-net ./main.ts"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
